# Generated by Django 5.1.7 on 2025-04-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('available', models.BooleanField(default=True)),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
